version: '3.8'

services:
  smocker:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        COMMIT: ${COMMIT:-local}
        GO_VERSION: 1.23
    container_name: smocker
    ports:
      - "8080:8080"  # Admin API and UI
      - "8081:8081"  # Mock server
    restart: unless-stopped
    environment:
      - SMOCKER_CONFIG_LISTEN_PORT=8080
      - SMOCKER_MOCK_SERVER_LISTEN_PORT=8081
